### ISSUE TITLE
Does it work for somoma? 

### ISSUE THREAD

**Issue by Pandaman123456** [1rocketdude/Optiplex_3050_SFF#1]

**Comment by 1rocketdude** [comment]
it didn’t work very well with BigSur, so I doubt it.
I was going to play with it today. The other implementation I’ve tried (https://github.com/mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050) did not work with Sonoma. Got to the “Install” button, but then shut down after 3 minutes.
I suspect USB ports are the problem. The hardware is most like a laptop, but I have been using iMac19,1.

let me know if you make progress. I’ll update my github if I can get something to work.

**Comment by 1rocketdude** [comment]
Here you go. Sometimes you get lucky.

I updated the EFI and got it to install/boot with Sonoma 14.2.1 on an M2.SSD. I’m guessing it’ll work on a SATA drive too.

sleep works - shocking!

what I can’t get to work is the Display Port. Tried multiple combinations of cables and connectors, but no go. Stuck with only a single monitor - the HDMI port.

I don’t have wifi on my 3050 SFF, so I don’t really test for it. I also didn’t test any of the apple handover stuff, which usually depends on wifi/bluetooth connectivity.

I only played with it for an hour, but the boot stability was far more reliable than when I created this EFI for BigSur.

let me know if you can get two monitors working. That’s a big deal for me.

cheers...

**Comment by 1rocketdude** [comment]
demonstrated against sonoma 14.2.1 and OC 0.9.7
